#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
 TWISTED BILAYER GRAPHENE (TBG) — BISTRITZER–MacDONALD (BM) CONTINUUM MODEL
================================================================================

 One valley (K), one spin. Two-layer continuum Hamiltonian:

   H = [ h_{-θ/2}(k)      T(r)†       ]
       [ T(r)             h_{+θ/2}(k) ]

 with intralayer Dirac cones  h_l(q) = -ħ v_F (q · R(∓θ/2) σ)  and interlayer
 coupling via the three tunneling matrices

   T_j = w_AA σ0 + w_AB [cos(jφ) σx + sin(jφ) σy],   φ = 2π/3,  j = 0,1,2

 which transfer momentum q_j, where q_0 = k_θ (0,-1) and q_1, q_2 are q_0
 rotated by ±120°, with  k_θ = 2|K| sin(θ/2)  and  |K| = 4π/(3a).

 "Relaxed" parameters (lattice corrugation): w_AA = 79.7 meV < w_AB = 97.5 meV.

 Outputs (PNG):
   fig1_bandas.png        — bands at large θ vs magic θ (path Γ→K→M→K'→Γ)
   fig2_barrido_theta.png — W(θ) of the two central bands + v*(θ)/v_F
   fig3_dos.png           — DOS: collapse of the van Hove peaks toward E = 0
   fig4_convergencia.png  — convergence with respect to the momentum cutoff

 Validations printed to the console:
   (1) the minimum of W(θ) falls at θ ≈ 1.05–1.10°,
   (2) approximate electron–hole symmetry of the spectrum,
   (3) convergence of the flat band with the cutoff radius.
================================================================================
"""

import time
import numpy as np
from scipy.linalg import eigvalsh
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ==============================================================================
# BLOCK 1 · Physical constants and tunneling matrices
# ==============================================================================
A_CC   = 0.246                     # graphene lattice constant [nm]
HBARVF = 2.1354 * A_CC             # ħ v_F = 2.1354 · a  [eV·nm]  (v_F ≈ 1e6 m/s)
K_DIRAC = 4.0 * np.pi / (3.0 * A_CC)   # |K| of monolayer graphene [nm^-1]
W_AA   = 0.0797                    # AA/BB tunneling [eV]  (relaxation: w_AA < w_AB)
W_AB   = 0.0975                    # AB/BA tunneling [eV]
PHI    = 2.0 * np.pi / 3.0

S0 = np.eye(2, dtype=complex)
SX = np.array([[0, 1], [1, 0]], dtype=complex)
SY = np.array([[0, -1j], [1j, 0]], dtype=complex)

# T_j = w_AA σ0 + w_AB [cos(jφ) σx + sin(jφ) σy],  j = 0, 1, 2
T_J = [W_AA * S0 + W_AB * (np.cos(j * PHI) * SX + np.sin(j * PHI) * SY)
       for j in range(3)]


# ==============================================================================
# BLOCK 2 · Moiré geometry
# ------------------------------------------------------------------------------
# Rotating the layers by ±θ/2 separates the Dirac points of the two layers by
# k_θ = 2|K| sin(θ/2). We choose coordinates with the layer-1 Dirac point at
# k = 0 (corner K_m of the mini-BZ); the layer-2 one sits at k = -q_0
# (corner K'_m). The three transfer vectors are q_0 = k_θ(0,-1) and its
# ±120° rotations; the moiré reciprocal lattice is generated by b1 = q_1-q_0,
# b2 = q_2-q_0 (|b| = √3 k_θ).
# ==============================================================================
def geometria(theta_deg):
    th = np.deg2rad(theta_deg)
    ktheta = 2.0 * K_DIRAC * np.sin(th / 2.0)
    qs = ktheta * np.array([[0.0, -1.0],
                            [ np.sqrt(3) / 2.0, 0.5],
                            [-np.sqrt(3) / 2.0, 0.5]])
    b1 = qs[1] - qs[0]
    b2 = qs[2] - qs[0]
    return ktheta, qs, b1, b2


# ==============================================================================
# BLOCK 3 · Truncated momentum basis (hexagonal grid with cutoff radius)
# ------------------------------------------------------------------------------
# Plane waves: layer 1 with momentum k + G, layer 2 with momentum k + G + q_0,
# G = m b1 + n b2. We truncate with a circle of radius R = N_sh·|b1| centered at
# q_0/2 (midpoint between the two Dirac "clouds"): this makes the basis symmetric
# under layer exchange, which preserves the model's approximate e-h symmetry and
# speeds up convergence.
# ==============================================================================
def base_momentos(n_sh, qs, b1, b2):
    centro = 0.5 * qs[0]
    radio = (n_sh + 1e-9) * np.linalg.norm(b1)
    m_max = n_sh + 3
    sitios1, sitios2 = [], []
    for m in range(-m_max, m_max + 1):
        for n in range(-m_max, m_max + 1):
            G = m * b1 + n * b2
            if np.linalg.norm(G - centro) <= radio:
                sitios1.append((m, n))
            if np.linalg.norm(G + qs[0] - centro) <= radio:
                sitios2.append((m, n))
    indice2 = {mn: i for i, mn in enumerate(sitios2)}
    return sitios1, sitios2, indice2


# ==============================================================================
# BLOCK 4 · BM Hamiltonian
# ------------------------------------------------------------------------------
# (a) Intralayer term: rotated Dirac cone,
#         h_l(p) = -ħ v_F (p · R(α_l) σ),   α_l = ∓θ/2,
#     and using  p·R(α)σ = (R(-α)p)·σ  we rotate the momentum instead of the σ.
# (b) Interlayer term: T_j connects layer 1 at G with layer 2 at G + Δ_j,
#     Δ_0 = 0, Δ_1 = b1, Δ_2 = b2  (equivalent to the transfer q_j).
#     This part does not depend on k, so it is built only once.
# ==============================================================================
def bloque_dirac(p, alpha):
    """Dirac cone of one layer rotated by an angle alpha (= ∓θ/2)."""
    c, s = np.cos(alpha), np.sin(alpha)
    px = c * p[0] + s * p[1]      # R(-alpha) · p
    py = -s * p[0] + c * p[1]
    return -HBARVF * np.array([[0.0, px - 1j * py],
                               [px + 1j * py, 0.0]])


def matriz_tunelaje(base):
    """Interlayer part of H (independent of k)."""
    s1, s2, idx2 = base
    n1, n2 = len(s1), len(s2)
    dim = 2 * (n1 + n2)
    off = 2 * n1
    HT = np.zeros((dim, dim), dtype=complex)
    desplaz = [(0, 0), (1, 0), (0, 1)]          # Δ_j in the {b1, b2} lattice
    for i, (m, n) in enumerate(s1):
        for j, (dm, dn) in enumerate(desplaz):
            destino = (m + dm, n + dn)
            if destino in idx2:
                i2 = idx2[destino]
                HT[off + 2 * i2: off + 2 * i2 + 2, 2 * i: 2 * i + 2] = T_J[j]
    HT += HT.conj().T
    return HT


def espectro_k(k, theta_deg, base, qs, b1, b2, HT, con_rotacion=True):
    """(Sorted) eigenvalues of H(k) for the given angle θ.

    con_rotacion=False suppresses the ∓θ/2 rotation of the cones: in that limit
    the BM model has EXACT electron–hole symmetry (P: k → -k-q0 + layer
    exchange), which we use as a numerical validation.
    """
    s1, s2, _ = base
    n1 = len(s1)
    off = 2 * n1
    th = np.deg2rad(theta_deg) if con_rotacion else 0.0
    H = HT.copy()
    for i, (m, n) in enumerate(s1):                       # layer 1, twist -θ/2
        p = k + m * b1 + n * b2
        H[2 * i: 2 * i + 2, 2 * i: 2 * i + 2] = bloque_dirac(p, -th / 2.0)
    for i, (m, n) in enumerate(s2):                       # layer 2, twist +θ/2
        p = k + m * b1 + n * b2 + qs[0]
        H[off + 2 * i: off + 2 * i + 2,
          off + 2 * i: off + 2 * i + 2] = bloque_dirac(p, +th / 2.0)
    return eigvalsh(H)


def preparar(theta_deg, n_sh):
    """Geometry + basis + static part of H for a given θ."""
    ktheta, qs, b1, b2 = geometria(theta_deg)
    base = base_momentos(n_sh, qs, b1, b2)
    HT = matriz_tunelaje(base)
    return ktheta, qs, b1, b2, base, HT


# ==============================================================================
# BLOCK 5 · High-symmetry path of the moiré mini-Brillouin-zone
# ------------------------------------------------------------------------------
# With the layer-1 Dirac point at the origin: K_m = (0,0), K'_m = (0, k_θ),
# M_m = (0, k_θ/2) and Γ_m = (√3/2, 1/2) k_θ  (|Γ-K| = k_θ, |Γ-M| = √3 k_θ/2).
# Requested path: Γ → K → M → K' → Γ.
# ==============================================================================
def camino_k(ktheta, pts_por_kt=48):
    nodos = [ktheta * np.array(v) for v in
             [(np.sqrt(3) / 2, 0.5), (0.0, 0.0), (0.0, 0.5),
              (0.0, 1.0), (np.sqrt(3) / 2, 0.5)]]
    etiquetas = ["Γ", "K", "M", "K'", "Γ"]
    ks, dist = [], []
    ticks = [0.0]
    d = 0.0
    for a, b in zip(nodos[:-1], nodos[1:]):
        L = np.linalg.norm(b - a)
        npts = max(8, int(round(pts_por_kt * L / ktheta)))
        for t in np.linspace(0.0, 1.0, npts, endpoint=False):
            ks.append(a + t * (b - a))
            dist.append(d + t * L)
        d += L
        ticks.append(d)
    ks.append(nodos[-1])
    dist.append(d)
    return np.array(ks), np.array(dist), ticks, etiquetas


def bandas_camino(theta_deg, n_sh, pts_por_kt=48):
    ktheta, qs, b1, b2, base, HT = preparar(theta_deg, n_sh)
    ks, dist, ticks, etiquetas = camino_k(ktheta, pts_por_kt)
    E = np.array([espectro_k(k, theta_deg, base, qs, b1, b2, HT) for k in ks])
    return dist, E, ticks, etiquetas


# ==============================================================================
# BLOCK 6 · Bandwidth of the two central bands over the whole mini-BZ
# ------------------------------------------------------------------------------
# Uniform grid k = (i/N) b1 + (j/N) b2 with N a multiple of 6, so that the
# grid contains exactly Γ, K, K' and M (where the extrema of the flat bands
# live). W = max E_sup − min E_inf over the mini-BZ.
# ==============================================================================
def ancho_bandas_centrales(theta_deg, n_sh=4, malla=6, devolver_extremos=False):
    ktheta, qs, b1, b2, base, HT = preparar(theta_deg, n_sh)
    dim = HT.shape[0]
    nb = dim // 2                                  # index of the upper central band
    e_inf, e_sup = [], []
    for i in range(malla):
        for j in range(malla):
            k = (i / malla) * b1 + (j / malla) * b2
            E = espectro_k(k, theta_deg, base, qs, b1, b2, HT)
            e_inf.append(E[nb - 1])
            e_sup.append(E[nb])
    e_inf, e_sup = np.array(e_inf), np.array(e_sup)
    W = e_sup.max() - e_inf.min()
    if devolver_extremos:
        return W, e_inf, e_sup
    return W


def velocidad_renormalizada(theta_deg, n_sh=4, dk_rel=1e-3):
    """v*/v_F from the SPLITTING of the cone at K_m (K→Γ direction).

    We use (E_sup − E_inf)/2 at K+δk instead of the absolute energy, because
    the set of flat bands has a small global energy shift (a physical breaking
    of e–h symmetry of order θ); the splitting removes that offset and gives the
    slope of the cone.
    """
    ktheta, qs, b1, b2, base, HT = preparar(theta_deg, n_sh)
    dim = HT.shape[0]
    nb = dim // 2
    dk = dk_rel * ktheta * np.array([np.sqrt(3) / 2.0, 0.5])
    E = espectro_k(dk, theta_deg, base, qs, b1, b2, HT)
    return (E[nb] - E[nb - 1]) / (2.0 * HBARVF * np.linalg.norm(dk))


# ==============================================================================
# BLOCK 7 · Density of states (DOS) with Gaussian broadening
# ==============================================================================
def dos(theta_deg, n_sh=4, malla=24, ventana=0.080, sigma=0.0015, n_e=701):
    ktheta, qs, b1, b2, base, HT = preparar(theta_deg, n_sh)
    energias = []
    for i in range(malla):
        for j in range(malla):
            k = ((i + 0.5) / malla) * b1 + ((j + 0.5) / malla) * b2
            E = espectro_k(k, theta_deg, base, qs, b1, b2, HT)
            energias.append(E[np.abs(E) < ventana + 6 * sigma])
    EE = np.concatenate(energias)
    eje = np.linspace(-ventana, ventana, n_e)
    rho = np.exp(-0.5 * ((eje[:, None] - EE[None, :]) / sigma) ** 2).sum(axis=1)
    rho /= (np.sqrt(2 * np.pi) * sigma * malla ** 2)   # states/(eV·moiré cell)
    return eje, rho


# ==============================================================================
# BLOCK 8 · Validations
# ==============================================================================
def validar_simetria_eh(theta_deg, n_sh=4, malla=12):
    """Electron–hole symmetry of the global spectrum over the mini-BZ.

    All energies of the 10 central bands collected on a symmetric grid are
    sorted: if the spectrum is e–h symmetric, S ≈ −S reversed.
    Returns (asymmetry WITH ∓θ/2 rotation, asymmetry WITHOUT rotation, span) in meV.
    Without rotation the P symmetry is exact → the asymmetry should be ~0 numerically;
    with rotation the physical breaking of order θ remains (small vs. the span).
    """
    ktheta, qs, b1, b2, base, HT = preparar(theta_deg, n_sh)
    dim = HT.shape[0]
    nb = dim // 2
    con, sin_ = [], []
    for i in range(malla):
        for j in range(malla):
            k = (i / malla) * b1 + (j / malla) * b2
            E1 = espectro_k(k, theta_deg, base, qs, b1, b2, HT, True)
            E0 = espectro_k(k, theta_deg, base, qs, b1, b2, HT, False)
            con.extend(E1[nb - 5: nb + 5])
            sin_.extend(E0[nb - 5: nb + 5])
    asim = lambda v: np.max(np.abs(np.sort(np.asarray(v)) +
                                   np.sort(np.asarray(v))[::-1])) * 1e3
    span = (np.max(con) - np.min(con)) * 1e3
    return asim(con), asim(sin_), span


def validar_convergencia(theta_deg, cortes=(2, 3, 4, 5, 6, 7), malla=6):
    """W(θ) as a function of the cutoff radius N_sh."""
    Ws, dims = [], []
    for n_sh in cortes:
        ktheta, qs, b1, b2, base, HT = preparar(theta_deg, n_sh)
        dims.append(HT.shape[0])
        Ws.append(ancho_bandas_centrales(theta_deg, n_sh=n_sh, malla=malla))
    return np.array(Ws), dims


# ==============================================================================
# BLOCK 9 · Figures
# ==============================================================================
plt.rcParams.update({
    "figure.dpi": 110, "savefig.dpi": 170, "font.size": 10,
    "axes.grid": True, "grid.alpha": 0.25, "axes.axisbelow": True,
})
GRIS, ROJO, AZUL = "#8a93a6", "#d6453d", "#2660a4"


def figura_bandas(theta_grande, theta_magico, n_sh, archivo):
    fig, axes = plt.subplots(1, 2, figsize=(10.5, 4.4))
    for ax, th in zip(axes, [theta_grande, theta_magico]):
        dist, E, ticks, lab = bandas_camino(th, n_sh)
        nb = E.shape[1] // 2
        for b in range(E.shape[1]):
            if abs(E[:, b]).min() < 0.30:
                ax.plot(dist, 1e3 * E[:, b], color=GRIS, lw=0.9)
        for b in (nb - 1, nb):
            ax.plot(dist, 1e3 * E[:, b], color=ROJO, lw=1.8)
        W = 1e3 * (E[:, nb].max() - E[:, nb - 1].min())
        ax.set_xticks(ticks); ax.set_xticklabels(lab)
        for t in ticks[1:-1]:
            ax.axvline(t, color="k", lw=0.5, alpha=0.3)
        ax.set_xlim(dist[0], dist[-1]); ax.set_ylim(-250, 250)
        ax.set_title(f"θ = {th:.2f}°   ·   W(path) = {W:.1f} meV")
        ax.set_ylabel("E  [meV]")
    # inset zoom of the flat bands in the magic-angle panel
    dist, E, ticks, lab = bandas_camino(theta_magico, n_sh)
    nb = E.shape[1] // 2
    axz = axes[1].inset_axes([0.58, 0.06, 0.40, 0.34])
    for b in (nb - 1, nb):
        axz.plot(dist, 1e3 * E[:, b], color=ROJO, lw=1.2)
    axz.set_xticks(ticks); axz.set_xticklabels(lab, fontsize=7)
    axz.set_ylim(-8, 8); axz.tick_params(labelsize=7); axz.grid(alpha=0.2)
    axz.set_title("flat-band zoom", fontsize=7)
    fig.suptitle("TBG BM bands (one valley) — path Γ→K→M→K'→Γ of the moiré mini-BZ")
    fig.tight_layout()
    fig.savefig(archivo)
    plt.close(fig)


def figura_barrido(thetas, Ws, vs, theta_estrella, archivo):
    fig, ax = plt.subplots(figsize=(7.2, 4.4))
    ax.semilogy(thetas, 1e3 * Ws, "o-", color=AZUL, ms=3.5, lw=1.4,
                label="W(θ): width of the 2 central bands")
    ax.axvspan(1.05, 1.10, color=ROJO, alpha=0.10,
               label="expected window 1.05–1.10°")
    ax.axvline(theta_estrella, color=ROJO, lw=1.4, ls="--",
               label=f"θ* = {theta_estrella:.3f}°  (minimum of W)")
    ax.set_xlabel("twist angle θ  [degrees]")
    ax.set_ylabel("W  [meV]  (log scale)")
    ax2 = ax.twinx()
    ax2.plot(thetas, vs, "s--", color="#3d8c5c", ms=3, lw=1.1, alpha=0.85)
    ax2.set_ylabel("v*/v_F  (renormalized Dirac velocity)", color="#3d8c5c")
    ax2.tick_params(axis="y", colors="#3d8c5c")
    ax2.set_ylim(bottom=-0.02)
    ax2.grid(False)
    ax.set_title("Flattening of the central bands and first magic angle")
    ax.legend(loc="upper center", fontsize=8)
    fig.tight_layout()
    fig.savefig(archivo)
    plt.close(fig)


def figura_dos(lista_th, n_sh, archivo):
    fig, ax = plt.subplots(figsize=(7.2, 4.8))
    colores = plt.cm.plasma(np.linspace(0.10, 0.78, len(lista_th)))
    paso = 1.15
    for i, th in enumerate(lista_th):
        eje, rho = dos(th, n_sh=n_sh)
        ax.plot(1e3 * eje, rho / rho.max() + paso * i, color=colores[i], lw=1.3)
        ax.text(62, paso * i + 0.55, f"θ = {th:.2f}°", color=colores[i],
                fontsize=9, weight="bold")
    ax.axvline(0, color="k", lw=0.7, alpha=0.5)
    ax.set_xlabel("E  [meV]")
    ax.set_ylabel("Normalized DOS (offset curves)")
    ax.set_yticks([])
    ax.set_title("Collapse of the van Hove singularities toward E = 0\n"
                 "as the magic angle is approached (one valley, one spin)")
    fig.tight_layout()
    fig.savefig(archivo)
    plt.close(fig)


def figura_convergencia(cortes, Ws, dims, archivo):
    fig, axes = plt.subplots(1, 2, figsize=(9.5, 3.9))
    axes[0].plot(cortes, 1e3 * Ws, "o-", color=AZUL)
    axes[0].axhline(1e3 * Ws[-1], color="k", lw=0.7, ls=":")
    axes[0].set_xlabel("cutoff radius  N_sh  (in units of |b₁|)")
    axes[0].set_ylabel("W  [meV]")
    axes[0].set_title("Flat-band W vs. cutoff")
    err = np.abs(Ws[:-1] - Ws[-1]) * 1e3
    axes[1].semilogy(cortes[:-1], np.maximum(err, 1e-9), "s-", color=ROJO)
    axes[1].set_xlabel("N_sh")
    axes[1].set_ylabel("|W(N) − W(N_max)|  [meV]")
    axes[1].set_title("Truncation error")
    for ax, c, d in [(axes[0], cortes, dims)]:
        for x, dd, y in zip(c, d, 1e3 * Ws):
            ax.annotate(f"dim {dd}", (x, y), textcoords="offset points",
                        xytext=(0, 8), fontsize=7, ha="center", color="#555")
    fig.suptitle("Convergence of the diagonalization with respect to the momentum cutoff")
    fig.tight_layout()
    fig.savefig(archivo)
    plt.close(fig)


# ==============================================================================
# BLOCK 10 · Main program
# ==============================================================================
def main():
    t0 = time.time()
    NSH = 4          # production cutoff radius (validated in Block 8)
    ok = []

    print("=" * 78)
    print(" TBG · BISTRITZER–MacDONALD CONTINUUM MODEL")
    print("=" * 78)
    print(f"  a = {A_CC} nm | ħv_F = {HBARVF:.5f} eV·nm | |K| = {K_DIRAC:.4f} nm⁻¹")
    print(f"  w_AA = {1e3*W_AA:.1f} meV | w_AB = {1e3*W_AB:.1f} meV "
          f"(η = w_AA/w_AB = {W_AA/W_AB:.3f})")

    # ---- 1) Twist-angle sweep: W(θ) and v*(θ) ------------------------------
    print("\n[1/4] θ sweep (6×6 grid over the mini-BZ, N_sh = 4)…")
    th_grueso = np.arange(0.70, 1.62, 0.02)
    W_grueso = np.array([ancho_bandas_centrales(t, NSH) for t in th_grueso])
    t_c = th_grueso[np.argmin(W_grueso)]
    th_fino = np.arange(t_c - 0.06, t_c + 0.0625, 0.005)
    W_fino = np.array([ancho_bandas_centrales(t, NSH) for t in th_fino])
    theta_estrella = th_fino[np.argmin(W_fino)]

    thetas = np.unique(np.concatenate([th_grueso, th_fino]))
    Ws = np.array([W_grueso[np.where(th_grueso == t)[0][0]]
                   if t in th_grueso else W_fino[np.where(th_fino == t)[0][0]]
                   for t in thetas])
    vs = np.array([velocidad_renormalizada(t, NSH) for t in thetas])

    W_estrella = ancho_bandas_centrales(theta_estrella, NSH, malla=12)
    print(f"      θ* = {theta_estrella:.3f}°  →  W = {1e3*W_estrella:.2f} meV "
          f"(12×12 grid),  v*/v_F = "
          f"{velocidad_renormalizada(theta_estrella, NSH):.4f}")
    val1 = 1.05 <= theta_estrella <= 1.10
    ok.append(val1)
    print(f"      VALIDATION 1 — minimum of W in 1.05° ≤ θ* ≤ 1.10°: "
          f"{'✓ PASS' if val1 else '✗ FAIL'}")
    figura_barrido(thetas, Ws, vs, theta_estrella, "fig2_barrido_theta.png")

    # ---- 2) Bands at given θ -------------------------------------------------
    print("\n[2/4] Band structure (Γ→K→M→K'→Γ) at θ = 1.50° and θ = θ*…")
    figura_bandas(1.50, theta_estrella, NSH, "fig1_bandas.png")

    # ---- 3) DOS and van Hove collapse ----------------------------------------
    print("\n[3/4] DOS at θ = 1.40°, 1.25°, 1.15° and θ* (24×24 grid)…")
    figura_dos([1.40, 1.25, 1.15, round(theta_estrella, 3)], NSH, "fig3_dos.png")

    # ---- 4) Validations: e–h symmetry and convergence ------------------------
    print("\n[4/4] e–h symmetry and convergence validations…")
    a_con, a_sin, span = validar_simetria_eh(theta_estrella, NSH)
    val2 = (a_sin < 1e-6) and (a_con < 0.05 * span)
    ok.append(val2)
    print(f"      e–h asymmetry (10 central bands, span = {span:.0f} meV):")
    print(f"        · WITHOUT ∓θ/2 rotation (exact P):  {a_sin:.2e} meV  → ~0 ✓")
    print(f"        · WITH ∓θ/2 rotation (physical):    {a_con:.3f} meV  "
          f"({100*a_con/span:.1f}% of the span)")
    print(f"      VALIDATION 2 — spectrum ≈ electron–hole symmetric: "
          f"{'✓ PASS' if val2 else '✗ FAIL'}")

    cortes = (2, 3, 4, 5, 6, 7)
    Wc, dims = validar_convergencia(theta_estrella, cortes)
    err_prod = abs(Wc[cortes.index(NSH)] - Wc[-1]) * 1e3
    val3 = err_prod < 0.10                           # < 0.1 meV with N_sh = 4
    ok.append(val3)
    print("      W(N_sh) [meV]: " +
          ", ".join(f"N={c}:{1e3*w:.3f}" for c, w in zip(cortes, Wc)))
    print(f"      Truncation error with N_sh = {NSH}: {err_prod:.4f} meV")
    print(f"      VALIDATION 3 — diagonalization converged with the cutoff: "
          f"{'✓ PASS' if val3 else '✗ FAIL'}")
    figura_convergencia(cortes, Wc, dims, "fig4_convergencia.png")

    print("\n" + "=" * 78)
    print(f" SUMMARY: {sum(ok)}/3 validations passed · "
          f"θ* = {theta_estrella:.3f}° · W(θ*) = {1e3*W_estrella:.2f} meV · "
          f"{time.time()-t0:.0f} s")
    print(" Figures: fig1_bandas.png, fig2_barrido_theta.png, "
          "fig3_dos.png, fig4_convergencia.png")
    print("=" * 78)


if __name__ == "__main__":
    main()
